[tools]
"aqua:starship/starship" = "latest"
"aqua:cli/cli" = "latest"
"aqua:x-motemen/ghq" = "latest"
"aqua:d-kuro/gwq" = "latest"
"aqua:junegunn/fzf" = "latest"

[env]
_.path = ["~/.local/bin"]

[settings]
trusted_config_paths = [
  "~/ghq/github.com/25MPOOL",
  "~/ghq/github.com/miyakoshi-3854"
]